# Generated by Django 6.1 on 2026-09-10 13:56

import django.core.validators
import netbox_atlas.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_atlas', '0002_floorlayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorlayer',
            name='file',
            field=models.FileField(blank=True, upload_to=netbox_atlas.models.layer_upload_path, validators=[netbox_atlas.models.validate_layer_image]),
        ),
        migrations.AlterField(
            model_name='floorlayer',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
