# Generated by Django 6.1 on 2026-09-08 08:22

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_spatial_lens.models
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0144_customfield_status'),
        ('netbox_spatial_lens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, upload_to=netbox_spatial_lens.models.layer_upload_path)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('x', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('y', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('width', models.DecimalField(decimal_places=1, max_digits=8)),
                ('height', models.DecimalField(decimal_places=1, max_digits=8)),
                ('rotation', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359.9)])),
                ('opacity', models.DecimalField(decimal_places=2, default=0.6, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='netbox_spatial_lens.floor')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'background layer',
                'ordering': ('floor', 'weight', 'name'),
                'constraints': [models.UniqueConstraint(fields=('floor', 'name'), name='netbox_spatial_lens_floorlayer_unique_floor_name')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
